Repository jangle401/jangle-front, pull requests merged in 2021-12, with the labels that each got.

#4 Add project preparation documents
  docs/Pitch.md
  docs/TeamAgreement.md
Labels: documentation

#16 Staging
  .eslintrc.json
  .prettierignore
  .prettierrc.json
  README.md
  docs/Pitch.md
  docs/Requirements.md
  docs/TeamAgreement.md
  img/docs/domain-model.png
  img/docs/schema.png
  img/docs/wireframe.png
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/main.js
  src/App.css
  src/App.js
  src/components/AuthButtons.js
  src/components/Header.js
  src/components/LeftSidebar.js
  src/components/RightSidebar.js
  src/components/mainContainer/Landing.js
  src/components/mainContainer/Matcher.js
  src/components/mainContainer/Roomchat.js
  src/components/mainContainer/index.js
  src/components/roomChatLeftSidebar/MatcherButton.js
  src/components/roomChatLeftSidebar/MatcherSidebar.js
  src/components/roomChatLeftSidebar/Settings.js
  src/components/roomChatLeftSidebar/UserDetails.js
  src/components/roomChatLeftSidebar/index.js
  src/index.css
  src/index.js
Labels: documentation, enhancement

#33 User profile component refactor
  src/App.css
  src/components/Header.js
  src/components/auth/SignupButton.js
  src/components/auth/UserButton.js
  src/components/mainContainer/Landing.js
Labels: enhancement

#46 Add Direct Message component; Refactors Left Sidebar
  src/components/Sidebars/LeftSidebar/Chat/DirectMessage.js
  src/components/Sidebars/LeftSidebar/Chat/Private.js
  src/components/Sidebars/LeftSidebar/Chat/Public.js
  src/components/Sidebars/LeftSidebar/Chat/Rooms.js
  src/components/Sidebars/LeftSidebar/Chat/index.js
  src/components/Sidebars/LeftSidebar/Matcher/MatcherButton.js
  src/components/Sidebars/LeftSidebar/Matcher/MatcherSidebar.js
  src/components/Sidebars/LeftSidebar/index.js
  src/components/Sidebars/LeftSidebar/roomChatLeftSidebar/MatcherSidebar.js
  src/components/Sidebars/LeftSidebar/roomChatLeftSidebar/Settings.js
  src/components/Sidebars/LeftSidebar/roomChatLeftSidebar/UserDetails.js
  src/components/Sidebars/LeftSidebar/roomChatLeftSidebar/index.js
Labels: enhancement

#62 Fix memory leak in useEffect from Socket.io
  README.md
  src/App.scss
  src/components/Header.js
  src/components/Sidebars/LeftSidebar/Chat/CreateRoom.js
  src/components/Sidebars/LeftSidebar/Chat/CreateRoomForm.js
  src/components/Sidebars/LeftSidebar/Chat/DirectMessage.js
  src/components/Sidebars/LeftSidebar/Chat/Rooms.js
  src/components/Sidebars/RightSidebar/RoomUser.js
  src/components/Sidebars/RightSidebar/UserList.js
  src/components/mainContainer/Landing.js
  src/components/mainContainer/Profile.js
  src/components/mainContainer/roomchat/MessageStream.js
  src/context/socket.js
  src/store/index.js
  src/store/rooms.js
Labels: enhancement

#63 Link to /profile route from user icon
  src/components/auth/UserButton.js
Labels: enhancement
